--
-- AIWorld: AgentGroup coalition/profile provenance (Milestone 2.12E4C2,
-- STATIC review P2 fix on 1deb4b2f9b18). AgentGroupRecord::Kind
-- (LOOSE/STABLE) alone was being used by AIWorldMgr::RunCoalitionMaintenance()
-- to decide which CoalitionFormationProfile's own automatic maintenance
-- rules (LeaveRadius, MinMembers) apply to a group - wrong, since Kind is
-- shared by every profile of that Kind (today only WolfLoose forms LOOSE
-- groups, but nothing about Kind alone stops a future second LOOSE-forming
-- profile from colliding the same way), and a manually/admin-created LOOSE
-- group would otherwise silently inherit WolfLoose's own automatic
-- leave/dissolve rules with no way to opt out.
--
-- profile_id is a new, persistent identity separate from kind: 0 (Invalid,
-- see CoalitionFormationProfileId.h) means no automatic formation profile
-- created this group - the correct, fail-closed value for every group that
-- predates this column, and for any group created manually/by an admin
-- tool from here on. A nonzero value names the specific
-- CoalitionFormationProfile (e.g. 1 = WolfLoose) whose own
-- RequestCreateGroup() call actually minted this group - only then is it
-- eligible for that profile's own automatic maintenance.
--
-- STATIC review (2.12E4C2): this backfill deliberately does NOT try to
-- guess which pre-existing rows were actually WolfLoose-formed - relabeling
-- an existing group's provenance without operator confirmation would be
-- exactly the false-provenance assignment this column exists to prevent.
-- A group an operator has independently confirmed is legitimately owned by
-- a real profile can be adopted after this migration runs via
-- AIWorld.AdoptGroupId/AIWorld.AdoptGroupProfileId (AIWorldMgr::
-- RunGroupProfileAdoption()) - a one-shot startup action that goes through
-- the existing AgentGroupPersistence API, never a raw UPDATE against this
-- table. profile_id's own numeric values are storage ABI from here on - see
-- CoalitionFormationProfileId.h for why they are explicit and never
-- recycled.
--
-- Every enumerator CoalitionFormationProfileId currently defines, for
-- reference: 0 = Invalid, 1 = WolfLoose.
--

ALTER TABLE `ai_agent_groups`
    ADD COLUMN `profile_id` TINYINT UNSIGNED NOT NULL DEFAULT 0 AFTER `version`;
